dataset:
  dataset_name: RadioMap
  dataset: ../radioMap/Boston/
  batch_size: 32
  num_workers: 1
  train_ratio: 0.2
  test_ratio: 0.7

model:
# ['DCLPA', 'EWC', 'MAS', 'LWF', 'ILT', 'RCM', 'MDIL', 'VANILLA', 'DEFORMABLE']
  model_name: 'LRRA'
  save_dir: checkpoints/lrra/
  tasks: ['USC','Boston','UCLA','SH']
  task: Boston
  # new_save_dir: checkpoints/DCLPA/

training:
  num_epochs: 120 
  lr: 0.0001
  seed: 42
  train_flag: False
  continue_train: False
  last_epoch: 15
  best_val_loss: 0.0334
  # ['MSE', 'KL', 'COS']
  loss: MSE
  checkpoint_path: checkpoints/lrra/

logs:
  train_logger_path: logs/lrra/
  test_logger_path: logs/lrra/


evaluation:
  model_path: checkpoints/lrra/


