dataset:
  dataset_name: RadioMap
  dataset: D:/Jimmy/pythonProjects/CL4PL_linux/dataset/radioMap/Boston/
  last_dataset: D:/Jimmy/pythonProjects/CL4PL_linux/dataset/radioMap/USC/
  batch_size: 32
  num_workers: 1
  train_ratio: 0.2
  test_ratio: 0.7

model:
# ['DCLPA', 'EWC', 'MAS', 'LWF', 'ILT', 'RCM', 'MDIL', 'VANILLA', 'DEFORMABLE']
  model_name: 'MAS'
  save_dir: checkpoints/mas/
  tasks: ['USC','Boston','UCLA','SH']
  task: Boston
  # new_save_dir: checkpoints/DCLPA/

training:
  num_epochs: 120 
  lr: 0.0001
  seed: 42
  train_flag: False
  continue_train: False
  last_epoch: 1
  best_val_loss: inf
  # ['MSE', 'KL', 'COS']
  loss: MSE
  checkpoint_path: checkpoints/mas/
  model_path: checkpoints/vanilla/USC_best_model.pth

logs:
  train_logger_path: logs/mas/
  test_logger_path: logs/mas/


evaluation:
  model_path: checkpoints/mas/


